### ISSUE TITLE
zene csatorna

### ISSUE THREAD

**Issue by Kacsloz** [VdszHun/VdszHun_Testing_Area#14]
**Kérdés:**
---esetleg van-e rá mód, hogy némítsuk a zene csatornát, így nem küld mindig értesítést a telefonom, ha valaki zenét "kér"?

**Fotók:**
---

**Egyéb ezzel kapcsolatban:**
---

**Comment by VdszHun** [comment]
Lehet magát a csatornát némítani a beállításaiban. Majd nézd meg holnap. :)

**Comment by VdszHun** [comment]
@Kacsloz  Meglett azóta?
